version: 2.1

jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run : |
             timeout: 1200
             chmod +x cocoa.sh
             ./cocoa.sh
